Repository OCA/repair, pull requests merged in 2023-08, with the labels that each got.

#17 [15.0][ADD] repair_reason
  repair_reason/README.rst
  repair_reason/__init__.py
  repair_reason/__manifest__.py
  repair_reason/models/__init__.py
  repair_reason/models/repair_order.py
  repair_reason/models/repair_reason.py
  repair_reason/readme/CONTRIBUTORS.rst
  repair_reason/readme/DESCRIPTION.rst
  repair_reason/readme/USAGE.rst
  repair_reason/security/ir.model.access.csv
  repair_reason/static/description/index.html
  repair_reason/tests/__init__.py
  repair_reason/tests/test_repair_reason.py
  repair_reason/views/repair_order_view.xml
  repair_reason/views/repair_reason_view.xml
  setup/repair_reason/odoo/addons/repair_reason
  setup/repair_reason/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#20 [15.0][ADD] repair_type_refurbish
  repair_type_refurbish/README.rst
  repair_type_refurbish/__init__.py
  repair_type_refurbish/__manifest__.py
  repair_type_refurbish/models/__init__.py
  repair_type_refurbish/models/repair.py
  repair_type_refurbish/models/repair_type.py
  repair_type_refurbish/readme/CONFIGURE.rst
  repair_type_refurbish/readme/CONTRIBUTORS.rst
  repair_type_refurbish/readme/DESCRIPTION.rst
  repair_type_refurbish/readme/USAGE.rst
  repair_type_refurbish/static/description/icon.png
  repair_type_refurbish/static/description/index.html
  repair_type_refurbish/tests/__init__.py
  repair_type_refurbish/tests/test_repair_type.py
  repair_type_refurbish/views/repair_type.xml
  setup/repair_type_refurbish/odoo/addons/repair_type_refurbish
  setup/repair_type_refurbish/setup.py
Labels: bot is merging ⏳

#22 [15.0][ADD] repair_security
  repair_security/README.rst
  repair_security/__init__.py
  repair_security/__manifest__.py
  repair_security/hook.py
  repair_security/readme/CONTRIBUTORS.rst
  repair_security/readme/DESCRIPTION.rst
  repair_security/security/ir.model.access.csv
  repair_security/security/repair_security.xml
  repair_security/views/repair_views.xml
  setup/repair_security/odoo/addons/repair_security
  setup/repair_security/setup.py
Labels: bot is merging ⏳

#21 [15.0][ADD] repair_type_sequence
  repair_type_sequence/README.rst
  repair_type_sequence/__init__.py
  repair_type_sequence/__manifest__.py
  repair_type_sequence/models/__init__.py
  repair_type_sequence/models/repair_order.py
  repair_type_sequence/models/repair_type.py
  repair_type_sequence/readme/CONTRIBUTORS.rst
  repair_type_sequence/readme/DESCRIPTION.rst
  repair_type_sequence/static/description/icon.png
  repair_type_sequence/static/description/index.html
  repair_type_sequence/tests/__init__.py
  repair_type_sequence/tests/test_repair_type.py
  repair_type_sequence/views/repair_type_views.xml
  setup/repair_type_sequence/odoo/addons/repair_type_sequence
  setup/repair_type_sequence/setup.py
Labels: approved, bot is merging ⏳
