Repository OCA/repair, pull requests merged in 2024-07, with the labels that each got.

#48 [16.0][MIG] repair_calendar_view: Migration to 16.0
  repair_calendar_view/README.rst
  repair_calendar_view/__init__.py
  repair_calendar_view/__manifest__.py
  repair_calendar_view/models/__init__.py
  repair_calendar_view/models/repair.py
  repair_calendar_view/readme/CONTRIBUTORS.rst
  repair_calendar_view/readme/DESCRIPTION.rst
  repair_calendar_view/readme/USAGE.rst
  repair_calendar_view/static/description/icon.png
  repair_calendar_view/static/description/index.html
  repair_calendar_view/tests/__init__.py
  repair_calendar_view/tests/test_repair_calendar_view.py
  repair_calendar_view/views/mrp_repair_view.xml
  setup/repair_calendar_view/odoo/addons/repair_calendar_view
  setup/repair_calendar_view/setup.py
Labels: bot is merging ⏳

#49 [16.0][MIG] repair_discount: Migration to 16.0
  repair_discount/README.rst
  repair_discount/__init__.py
  repair_discount/__manifest__.py
  repair_discount/i18n/de.po
  repair_discount/i18n/es.po
  repair_discount/i18n/fr.po
  repair_discount/i18n/hr.po
  repair_discount/i18n/hr_HR.po
  repair_discount/i18n/it.po
  repair_discount/i18n/lt.po
  repair_discount/i18n/mrp_repair_discount.pot
  repair_discount/i18n/nl_NL.po
  repair_discount/i18n/pt_BR.po
  repair_discount/i18n/repair_discount.pot
  repair_discount/models/__init__.py
  repair_discount/models/mrp_repair.py
  repair_discount/readme/CONTRIBUTORS.rst
  repair_discount/readme/DESCRIPTION.rst
  repair_discount/report/repair_templates_repair_order.xml
  repair_discount/static/description/icon.png
  repair_discount/static/description/index.html
  repair_discount/tests/__init__.py
  repair_discount/tests/test_mrp_repair_discount.py
  repair_discount/views/mrp_repair_view.xml
  setup/repair_discount/odoo/addons/repair_discount
  setup/repair_discount/setup.py
Labels: approved, bot is merging ⏳

#43 [17.0][MIG] repair_type: Migration to 17.0
  repair_type/README.rst
  repair_type/__init__.py
  repair_type/__manifest__.py
  repair_type/i18n/es.po
  repair_type/i18n/hr.po
  repair_type/i18n/it.po
  repair_type/i18n/repair_type.pot
  repair_type/migrations/17.0.1.0.0/pre-migration.py
  repair_type/models/__init__.py
  repair_type/models/stock_move.py
  repair_type/models/stock_picking_type.py
  repair_type/pyproject.toml
  repair_type/readme/CONTRIBUTORS.md
  repair_type/readme/DESCRIPTION.md
  repair_type/readme/USAGE.md
  repair_type/static/description/icon.png
  repair_type/static/description/index.html
  repair_type/tests/__init__.py
  repair_type/tests/test_repair_type.py
  repair_type/views/stock_picking_type_views.xml
Labels: approved, bot is merging ⏳, ready to merge
