Repository OCA/repair, pull requests merged in 2024-03, with the labels that each got.

#40 [15.0][ADD] repair_type_security
  repair_type_security/README.rst
  repair_type_security/__init__.py
  repair_type_security/__manifest__.py
  repair_type_security/hook.py
  repair_type_security/readme/CONTRIBUTORS.rst
  repair_type_security/readme/DESCRIPTION.rst
  repair_type_security/security/ir.model.access.csv
  repair_type_security/static/description/icon.png
  repair_type_security/static/description/index.html
  setup/repair_type_security/odoo/addons/repair_type_security
  setup/repair_type_security/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#24 [15.0][FIX] repair_refurbish: refurbish should not be the default option even if there is a refurbish product
  repair_refurbish/models/repair.py
  repair_refurbish/tests/test_repair_refurbish.py
Labels: bot is merging ⏳

#33 [16.0][MIG] repair_type_sequence: Migration to 16.0
  repair_type_sequence/README.rst
  repair_type_sequence/__init__.py
  repair_type_sequence/__manifest__.py
  repair_type_sequence/i18n/repair_type_sequence.pot
  repair_type_sequence/models/__init__.py
  repair_type_sequence/models/repair_order.py
  repair_type_sequence/models/repair_type.py
  repair_type_sequence/readme/CONTRIBUTORS.rst
  repair_type_sequence/readme/DESCRIPTION.rst
  repair_type_sequence/static/description/icon.png
  repair_type_sequence/static/description/index.html
  repair_type_sequence/tests/__init__.py
  repair_type_sequence/tests/test_repair_type.py
  repair_type_sequence/views/repair_type_views.xml
  setup/repair_type_sequence/odoo/addons/repair_type_sequence
  setup/repair_type_sequence/setup.py
Labels: bot is merging ⏳

#28 [16.0][FIX] repair_type: Call super for location_id in Repair Line
  repair_type/models/repair.py
Labels: approved, bot is merging ⏳

#38 [16.0][FIX] repair_sale_order: keep shipping address
  repair_sale_order/models/repair_order.py
  repair_sale_order/tests/test_repair_sale_order.py
Labels: approved, bot is merging ⏳

#23 [16.0][MIG] repair_refurbish: Migration to 16.0
  repair_refurbish/README.rst
  repair_refurbish/__init__.py
  repair_refurbish/__manifest__.py
  repair_refurbish/data/stock_data.xml
  repair_refurbish/i18n/de.po
  repair_refurbish/i18n/mrp_repair_refurbish.pot
  repair_refurbish/i18n/repair_refurbish.pot
  repair_refurbish/models/__init__.py
  repair_refurbish/models/product_product.py
  repair_refurbish/models/product_template.py
  repair_refurbish/models/repair.py
  repair_refurbish/models/stock_move.py
  repair_refurbish/readme/CONFIGURE.rst
  repair_refurbish/readme/CONTRIBUTORS.rst
  repair_refurbish/readme/CREDITS.rst
  repair_refurbish/readme/DESCRIPTION.rst
  repair_refurbish/readme/USAGE.rst
  repair_refurbish/static/description/icon.png
  repair_refurbish/static/description/index.html
  repair_refurbish/tests/__init__.py
  repair_refurbish/tests/test_repair_refurbish.py
  repair_refurbish/views/product_product_view.xml
  repair_refurbish/views/product_template_view.xml
  repair_refurbish/views/repair_view.xml
  setup/repair_refurbish/odoo/addons/repair_refurbish
  setup/repair_refurbish/setup.py
Labels: approved, bot is merging ⏳

#34 [16.0][MIG] repair_type_refurbish: Migration to 16.0
  repair_type_refurbish/README.rst
  repair_type_refurbish/__init__.py
  repair_type_refurbish/__manifest__.py
  repair_type_refurbish/i18n/repair_type_refurbish.pot
  repair_type_refurbish/models/__init__.py
  repair_type_refurbish/models/repair.py
  repair_type_refurbish/models/repair_type.py
  repair_type_refurbish/readme/CONFIGURE.rst
  repair_type_refurbish/readme/CONTRIBUTORS.rst
  repair_type_refurbish/readme/DESCRIPTION.rst
  repair_type_refurbish/readme/USAGE.rst
  repair_type_refurbish/static/description/icon.png
  repair_type_refurbish/static/description/index.html
  repair_type_refurbish/tests/__init__.py
  repair_type_refurbish/tests/test_repair_type.py
  repair_type_refurbish/views/repair_type.xml
  setup/repair_type_refurbish/odoo/addons/repair_type_refurbish
  setup/repair_type_refurbish/setup.py
Labels: bot is merging ⏳
