Repository OCA/repair, pull requests merged in 2025-02, with the labels that each got.

#87 [17.0][IMP] repair_stock: bump dev status
  repair_stock/__manifest__.py
Labels: approved, bot is merging ⏳

#88 [17.0][ADD] repair_restrict_lot
  repair_restrict_lot/README.rst
  repair_restrict_lot/__init__.py
  repair_restrict_lot/__manifest__.py
  repair_restrict_lot/pyproject.toml
  repair_restrict_lot/readme/CONTRIBUTORS.md
  repair_restrict_lot/readme/DESCRIPTION.md
  repair_restrict_lot/readme/USAGE.md
  repair_restrict_lot/static/description/icon.png
  repair_restrict_lot/static/description/index.html
  repair_restrict_lot/views/repair_order_view.xml
Labels: approved, bot is merging ⏳

#89 [17.0][FIX] repair_type: default remove and recycle source locations
  repair_type/models/stock_picking_type.py
Labels: approved, bot is merging ⏳

#90 [17.0][IMP] repair_stock: use a non conflicting field for auxiliar transfers
  repair_stock/models/__init__.py
  repair_stock/models/repair.py
  repair_stock/models/stock_move.py
  repair_stock/models/stock_rule.py
  repair_stock/tests/test_stock_repair_order.py
Labels: approved, bot is merging ⏳

#91 [17.0][REF] repair_refurbish: refactor to adapt to new repair in v17
  repair_refurbish/README.rst
  repair_refurbish/__manifest__.py
  repair_refurbish/models/repair.py
  repair_refurbish/models/stock_move.py
  repair_refurbish/readme/USAGE.md
  repair_refurbish/static/description/index.html
  repair_refurbish/tests/test_repair_refurbish.py
  repair_refurbish/views/repair_view.xml
Labels: approved, bot is merging ⏳

#78 [18.0][MIG] repair_type: Migration to 18.0
  repair_type/README.rst
  repair_type/__init__.py
  repair_type/__manifest__.py
  repair_type/i18n/es.po
  repair_type/i18n/hr.po
  repair_type/i18n/it.po
  repair_type/i18n/repair_type.pot
  repair_type/models/__init__.py
  repair_type/models/stock_move.py
  repair_type/models/stock_picking_type.py
  repair_type/pyproject.toml
  repair_type/readme/CONTRIBUTORS.md
  repair_type/readme/DESCRIPTION.md
  repair_type/readme/USAGE.md
  repair_type/static/description/icon.png
  repair_type/static/description/index.html
  repair_type/tests/__init__.py
  repair_type/tests/test_repair_type.py
  repair_type/views/stock_picking_type_views.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#86 [17.0][MIG] repair_picking
  repair_picking/README.rst
  repair_picking/__init__.py
  repair_picking/__manifest__.py
  repair_picking/i18n/it.po
  repair_picking/i18n/repair_picking.pot
  repair_picking/migrations/17.0.1.0.0/pre-migration.py
  repair_picking/models/__init__.py
  repair_picking/models/procurement_group.py
  repair_picking/models/repair.py
  repair_picking/models/stock_move.py
  repair_picking/models/stock_warehouse.py
  repair_picking/pyproject.toml
  repair_picking/readme/CONFIGURE.md
  repair_picking/readme/CONTRIBUTORS.md
  repair_picking/readme/DESCRIPTION.md
  repair_picking/readme/USAGE.md
  repair_picking/static/description/icon.png
  repair_picking/static/description/index.html
  repair_picking/tests/__init__.py
  repair_picking/tests/test_stock_repair_order.py
  repair_picking/tests/test_stock_repair_warehouse.py
  repair_picking/views/stock_warehouse_views.xml
Labels: approved, ready to merge

#96 [16.0][MIG][BCK] repair_quality_control: Migration - Backport from 17.0
  repair_quality_control/README.rst
  repair_quality_control/__init__.py
  repair_quality_control/__manifest__.py
  repair_quality_control/i18n/ca_ES.po
  repair_quality_control/i18n/es.po
  repair_quality_control/i18n/it.po
  repair_quality_control/i18n/repair_quality_control.pot
  repair_quality_control/models/__init__.py
  repair_quality_control/models/qc_inspection.py
  repair_quality_control/models/repair.py
  repair_quality_control/readme/CONTRIBUTORS.md
  repair_quality_control/readme/DESCRIPTION.md
  repair_quality_control/readme/USAGE.md
  repair_quality_control/static/description/icon.png
  repair_quality_control/static/description/icon.svg
  repair_quality_control/static/description/index.html
  repair_quality_control/tests/__init__.py
  repair_quality_control/tests/test_repair_quality_control.py
  repair_quality_control/views/qc_inspection_views.xml
  repair_quality_control/views/repair_views.xml
  setup/repair_quality_control/odoo/addons/repair_quality_control
  setup/repair_quality_control/setup.py
Labels: approved, bot is merging ⏳
